import { Title } from "./types"

const now = new Date().toISOString()
const yesterday = new Date(Date.now() - 86400000).toISOString()
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString()

export const MOCK_TITLES: Title[] = [
  {
    id: "1",
    user_id: "mock_user",
    title: "Solo Leveling",
    genres: ['Action', 'Fantasy'],
    media_type: "manhwa",
    cover_url: "https://cdn.myanimelist.net/images/manga/3/222295l.jpg",
    total_chapters: 179,
    current_chapter: 179,
    total_volumes: null,
    current_volume: 0,
    status: "completed",
    rating: 5,
    notes: "Masterpiece.",
    is_favorite: true,
    started_at: lastWeek,
    completed_at: yesterday,
    created_at: lastWeek,
    updated_at: yesterday,
  },
  {
    id: "2",
    user_id: "mock_user",
    title: "Omniscient Reader's Viewpoint",
    genres: ['Action', 'Fantasy', 'Mystery'],
    media_type: "manhwa",
    cover_url: "https://cdn.myanimelist.net/images/manga/1/262699l.jpg",
    total_chapters: null,
    current_chapter: 215,
    total_volumes: null,
    current_volume: 0,
    status: "reading",
    rating: 5,
    notes: "",
    is_favorite: true,
    started_at: lastWeek,
    completed_at: null,
    created_at: lastWeek,
    updated_at: now,
  },
  {
    id: "3",
    user_id: "mock_user",
    title: "Berserk",
    genres: ['Action', 'Adventure', 'Drama'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/1/157897l.jpg",
    total_chapters: 375,
    current_chapter: 120,
    total_volumes: null,
    current_volume: 0,
    status: "reading",
    rating: 5,
    notes: "Incredible art.",
    is_favorite: true,
    started_at: lastWeek,
    completed_at: null,
    created_at: lastWeek,
    updated_at: now,
  },
  {
    id: "4",
    user_id: "mock_user",
    title: "Chainsaw Man",
    genres: ['Action', 'Adventure'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/3/216464l.jpg",
    total_chapters: null,
    current_chapter: 160,
    total_volumes: null,
    current_volume: 0,
    status: "reading",
    rating: 4,
    notes: "Crazy story",
    is_favorite: false,
    started_at: lastWeek,
    completed_at: null,
    created_at: lastWeek,
    updated_at: yesterday,
  },
  {
    id: "5",
    user_id: "mock_user",
    title: "The Beginning After The End",
    genres: ['Action', 'Adventure'],
    media_type: "light_novel",
    cover_url: "https://cdn.myanimelist.net/images/manga/1/230542l.jpg",
    total_chapters: 480,
    current_chapter: 0,
    total_volumes: null,
    current_volume: 0,
    status: "want_to_read",
    rating: null,
    notes: "Recommended by friend",
    is_favorite: false,
    started_at: null,
    completed_at: null,
    created_at: yesterday,
    updated_at: yesterday,
  },
  {
    id: "6",
    user_id: "mock_user",
    title: "Vagabond",
    genres: ['Action', 'Adventure', 'Drama'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/2/181787l.jpg",
    total_chapters: 327,
    current_chapter: 15,
    total_volumes: null,
    current_volume: 0,
    status: "on_hold",
    rating: 4,
    notes: "Taking a break.",
    is_favorite: false,
    started_at: lastWeek,
    completed_at: null,
    created_at: lastWeek,
    updated_at: yesterday,
  },
  {
    id: "7",
    user_id: "mock_user",
    title: "Tower of God",
    genres: ['Action', 'Adventure'],
    media_type: "manhwa",
    cover_url: "https://cdn.myanimelist.net/images/manga/1/233651l.jpg",
    total_chapters: null,
    current_chapter: 50,
    total_volumes: null,
    current_volume: 0,
    status: "dropped",
    rating: 2,
    notes: "Too slow for me.",
    is_favorite: false,
    started_at: lastWeek,
    completed_at: null,
    created_at: lastWeek,
    updated_at: yesterday,
  },
  {
    id: "8",
    user_id: "mock_user",
    title: "One Piece",
    genres: ['Action', 'Adventure', 'Fantasy'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/2/253146l.jpg",
    total_chapters: null,
    current_chapter: 1080,
    total_volumes: null,
    current_volume: 0,
    status: "reading",
    rating: 5,
    notes: "Peak fiction",
    is_favorite: true,
    started_at: "2023-01-01T00:00:00Z",
    completed_at: null,
    created_at: "2023-01-01T00:00:00Z",
    updated_at: now,
  },
  {
    id: "9",
    user_id: "mock_user",
    title: "Monster",
    genres: ['Action', 'Adventure'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/3/258224l.jpg",
    total_chapters: 162,
    current_chapter: 162,
    total_volumes: null,
    current_volume: 0,
    status: "completed",
    rating: 5,
    notes: "A masterpiece of psychological thriller",
    is_favorite: true,
    started_at: "2023-02-01T00:00:00Z",
    completed_at: "2023-03-01T00:00:00Z",
    created_at: "2023-02-01T00:00:00Z",
    updated_at: "2023-03-01T00:00:00Z",
  },
  {
    id: "10",
    user_id: "mock_user",
    title: "Mushoku Tensei",
    genres: ['Action', 'Adventure'],
    media_type: "light_novel",
    cover_url: "https://cdn.myanimelist.net/images/manga/2/198773l.jpg",
    total_chapters: 26,
    current_chapter: 10,
    total_volumes: null,
    current_volume: 0,
    status: "reading",
    rating: 4,
    notes: "Good worldbuilding",
    is_favorite: false,
    started_at: lastWeek,
    completed_at: null,
    created_at: lastWeek,
    updated_at: yesterday,
  },
  {
    id: "11",
    user_id: "mock_user",
    title: "Spy x Family",
    genres: ['Action', 'Adventure'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/3/219513l.jpg",
    total_chapters: null,
    current_chapter: 0,
    total_volumes: null,
    current_volume: 0,
    status: "want_to_read",
    rating: null,
    notes: "",
    is_favorite: false,
    started_at: null,
    completed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "12",
    user_id: "mock_user",
    title: "Overgeared",
    genres: ['Action', 'Adventure'],
    media_type: "light_novel",
    cover_url: "https://cdn.myanimelist.net/images/manga/3/252467l.jpg",
    total_chapters: 2000,
    current_chapter: 750,
    total_volumes: null,
    current_volume: 0,
    status: "on_hold",
    rating: 3,
    notes: "Need a break from it",
    is_favorite: false,
    started_at: "2023-05-01T00:00:00Z",
    completed_at: null,
    created_at: "2023-05-01T00:00:00Z",
    updated_at: yesterday,
  },
  {
    id: "13",
    user_id: "mock_user",
    title: "Bleach",
    genres: ['Action', 'Adventure'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/3/249657l.jpg",
    total_chapters: 686,
    current_chapter: 686,
    total_volumes: null,
    current_volume: 0,
    status: "completed",
    rating: 4,
    notes: "",
    is_favorite: false,
    started_at: "2022-01-01T00:00:00Z",
    completed_at: "2022-12-01T00:00:00Z",
    created_at: "2022-01-01T00:00:00Z",
    updated_at: "2022-12-01T00:00:00Z",
  },
  {
    id: "14",
    user_id: "mock_user",
    title: "Naruto",
    genres: ['Action', 'Adventure'],
    media_type: "manga",
    cover_url: "https://cdn.myanimelist.net/images/manga/3/249658l.jpg",
    total_chapters: 700,
    current_chapter: 0,
    total_volumes: null,
    current_volume: 0,
    status: "reading",
    rating: null,
    notes: "",
    is_favorite: false,
    started_at: lastWeek,
    completed_at: null,
    created_at: lastWeek,
    updated_at: lastWeek,
  }
]

